language: php

services:
    - mysql
    - postgresql

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - DB_CONNECTION=sqlite
        - DB_DATABASE=":memory:"
        - COVERAGE=yes

php:
    - 7.2
    - 7.3
    - 7.4snapshot

matrix:
    include:
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=pgsql DB_DATABASE=test DB_USERNAME=postgres DB_PASSWORD=
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=mysql MYSQL=8 DB_DATABASE=test DB_USERNAME=root DB_PASSWORD=
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=mysql DB_DATABASE=test DB_USERNAME=root DB_PASSWORD=
        - php: 7.2
          env: DB_CONNECTION=sqlsrv DB_DATABASE=test DB_USERNAME=sa DB_PASSWORD="Password!"
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=pgsql DB_DATABASE=test DB_USERNAME=postgres DB_PASSWORD=
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=mysql MYSQL=8 DB_DATABASE=test DB_USERNAME=root DB_PASSWORD=
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=mysql DB_DATABASE=test DB_USERNAME=root DB_PASSWORD=
        - php: 7.3
          env: DB_CONNECTION=sqlsrv DB_DATABASE=test DB_USERNAME=sa DB_PASSWORD="Password!"
    allow_failures:
        - php: 7.4snapshot

before_install:
    - |
        if [ $MYSQL == "8" ]; then
          wget https://dev.mysql.com/get/mysql-apt-config_0.8.13-1_all.deb
          sudo dpkg -i mysql-apt-config_0.8.13-1_all.deb
          sudo apt-get update
          sudo apt-get install -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
          sudo systemctl restart mysql
        fi
    - mysql -e 'CREATE DATABASE test;'
    - psql -c 'create database test;' -U postgres
    - |
        if [ $DB_CONNECTION == "sqlsrv" ]; then
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list | sudo tee /etc/apt/sources.list.d/mssql-server-2017.list
          sudo apt-get update
          sudo apt-get install mssql-server
          sudo MSSQL_SA_PASSWORD=Password! MSSQL_PID=developer /opt/mssql/bin/mssql-conf -n setup accept-eula
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install mssql-tools unixodbc-dev
          pecl install pdo_sqlsrv
          sudo /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Password! -Q "create database [test]"
        fi

install:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - |
        if [ $DB_CONNECTION == "mysql" ]; then
            mysql --version
        fi
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - |
        if [ $COVERAGE == "yes" ]; then
          travis_retry wget https://scrutinizer-ci.com/ocular.phar
          travis_retry php ocular.phar code-coverage:upload --format=php-clover coverage.xml
        fi